### ISSUE TITLE
Provide a point-view for the geo-location tagged tweets

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#157]
plot the tweets by it's geolocation as a point. 

It could be implemented by using the `geocell` function of the new data model.

**Comment by JavierJia** [comment]
The aggregation result is easy to show. The harder problem is to show the information on data points.

**Comment by JavierJia** [comment]
The "topK" may not serve the purpose directly. What we need is a "top10%" instead of "top100" result. Does *db support this query?

**Comment by JavierJia** [comment]
@simonmssu

**Comment by JavierJia** [comment]
Get an idea from a discussion in SIGSPATIAL: issue a aggregation result for each very small cell.

**Comment by JavierJia** [comment]
@zonghengma we can do it step by step. 
The first step just show all points within a small region. e.g., when we zoom to a layer finner then city, we show all points in that region.

**Comment by JavierJia** [comment]
@HotLemonJuice , could you *move* the issue content you just created to here? thanks!

**Comment by HotLemonJuice** [comment]
So far we are using a heat map to show the Tweets on the map. It is a high-level description of the data.

Now if we can show the exact location of each Tweet, we can make the connection between the data and the geolocation closer.

A good example by MapD:
https://www.mapd.com/demos/tweetmap/
![screen shot 2017-03-06 at 16 41 41](https://cloud.githubusercontent.com/assets/12385178/23636764/389961c8-028c-11e7-92f1-d80b57434ac0.jpg)

However, since there are too much data to load in the browser, we need use some tricks to avoid crashing the browser. We can start implementing this feature in small areas of the map, e.g. city level.

**Comment by HotLemonJuice** [comment]
There aren't much point data in the sample data. How do I add fake data into the DB?

**Comment by JavierJia** [comment]
we can generate a sample data. for now, you may use the field of `"bounding_box": rectangle("-74.146932,40.643773 -74.0658,40.697794") }`?  you can just pick the first value, and add some random value.

**Comment by JavierJia** [comment]
you can take a look at the `sample.data` under `script` folder. Here is an example of the `place` field
```
"place": { "country": "United States", "country_code": "United States", "full_name": "Houston, TX", "id": "1c69a67ad480e1b1", "name": "Houston", "place_type": "city", "bounding_box": rectangle("-95.823268,29.522325 -95.069705,30.154665") }
```

**Comment by HotLemonJuice** [comment]
Notes for future dev:
- use city ID and existing coordinate to show points (if some piece of data doesn't contain them, we just don't show them)
- use `L.circleMarker` to display points on the map
- checkout the js controller for the hashtag. It has the information of city ID...

Now, I'm switching off to Normalization as it is more urgent
