### ISSUE TITLE
[FE][Pin map] Tweet pop-up where the mouse is not at the exact location of a point

### ISSUE THREAD

**Issue by ruig2** [ISG-ICS/cloudberry#614]
The twitter message box is popped-up where the cursor is rather than where the blue point is. That means if you move your mouse quickly, then it would pop-up somewhere else.

We can fix the above issue by showing the pop-up message where the **blue pinned point** is rather than where the mouse cursor is.

**Comment by ruig2** [comment]
Related video showing the bug is uploaded to Slack: https://cloudberry-uci.slack.com/files/UAB75AP6K/FE34PT7C7/cloudberry_twitter_shift.mov

**Comment by ruig2** [comment]
It seems that I cannot reproduce that on prod environment: http://cloudberry.ics.uci.edu/apps/twittermap

Maybe the latency in dev env is longer than that on prod env?

**Comment by baiqiushi** [comment]
This issue is still unsolved. It's related to the way of how `webgl-points-layer.js` library checks whether there's a point at the location of the mouse cursor. I tried to resolve it by re-call the getting pointID function right before creating the popup window. However it does resolve the issue. So we need some deeper look into the problem.

**Comment by chenlica** [comment]
Let's discuss it F2F.

**Comment by baiqiushi** [comment]
Low priority.
