### ISSUE TITLE
Collecting Zika-related emails from Dow Jones Factiva

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#68]
Dow Jones Factiva: http://www.dowjones.com/products/product-factiva/

@JavierJia

**Comment by xuxip** [comment]
Factiva search tool supports keyword search and boolean search. We are not able to reach it now because A corporate account (corporate ID and password are required) is required.

The following link is the Factiva 'Search' tutorial:
https://www.youtube.com/watch?v=7nEi1utOmGE&index=3&list=PLe4wcUqIo_s_NHY1EXoFvdr9ZmpCrc3p_

**Comment by JavierJia** [comment]
Blocked.
