### ISSUE TITLE
Add an AWS load balancer

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#738]
In case the Web traffic increases, we need to use an AWS load balancer in front of multiple servers.

**Comment by Yicong-Huang** [comment]
In order to do AWS load balancer, the Apache conf has to be changed. 

1. Port 443 should handle all domain names, not just a specific domain. Because load balancer will forward the request with an internal ip. 

2. Some HTTP proxies are unused, can be removed.

3. Combine WSS proxies to one, to minimize the configuration.

**Comment by baiqiushi** [comment]
Done.
